name: Python CI/CD Suma

on:
  push:
  workflow_dispatch:
    inputs:
      num1:
        description: 'Ingresa el primer número'
        required: false
        default: '15'
      num2:
        description: 'Ingresa el segundo número'
        required: false
        default: '25'

jobs:
  # Trabajo 1: Realiza las pruebas y ejecuta el script en Python
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Ejecutar prueba de suma con Python
      run: python sumar.py "${{ github.event.inputs.num1 }}" "${{ github.event.inputs.num2 }}"

  # Trabajo 2: Se conecta a 'test' y genera el enlace azul en la caja gráfica
  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: Produccion
      url: https://org-core701.github.io/repo-suma
    steps:
    - name: Confirmar despliegue
      run: echo "Despliegue completado con éxito."