name: Ejecutar Script Python de Suma

on:
  push:
  workflow_dispatch:
    inputs:
      num1:
        description: 'Ingresa el primer número'
        required: false
        default: '15'
      num2:
        description: 'Ingresa el segundo número'
        required: false
        default: '25'

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Ejecutar sumar.py
      run: python sumar.py "${{ github.event.inputs.num1 }}" "${{ github.event.inputs.num2 }}"